### ISSUE TITLE
Support for synchronous express state machines

### ISSUE THREAD

**Issue by StevenDas-Tomo** [terraform-aws-modules/terraform-aws-step-functions#1]
Hi all,

The SFN `CreateStateMachine` API call has a "type" parameter for explicitly tagging a state machine as either standard or express:

https://docs.aws.amazon.com/step-functions/latest/apireference/API_CreateStateMachine.html

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/stepfunctions.html#SFN.Client.create_state_machine

As far as I can tell, however, this Terraform module doesn't offer any way to specify the "type" of a state machine.

Are there any plans to add support for the "type" parameter? Or is this already possible today, and if so, how?

Our team is thinking of using a mix of standard and express state machines, so it would be useful to have the ability to customize this.

Thanks!

**Comment by antonbabenko** [comment]
Hi Steven,

There is an open issue in Terraform AWS provider about this - https://github.com/hashicorp/terraform-provider-aws/issues/11348

https://github.com/hashicorp/terraform-provider-aws/blob/master/ROADMAP.md - here it says that it will be taken into account in the near future. Once done we can have support for this in the module.

**Comment by StevenDas-Tomo** [comment]
Thanks, @antonbabenko!

**Comment by cojmcc** [comment]
I created a PR](https://github.com/terraform-aws-modules/terraform-aws-step-functions/pull/2) for this if you'd like to use the changes [

**Comment by antonbabenko** [comment]
Yes, I will review and merge this later this week. Thanks @cojmcc !

**Comment by antonbabenko** [comment]
Please use [v1.1.0](https://github.com/terraform-aws-modules/terraform-aws-step-function/releases/v1.1.0) which has been just released.
