### ISSUE TITLE
when deploying step functions with context execution id, not deploying as expected.

### ISSUE THREAD

**Issue by ghost** [terraform-aws-modules/terraform-aws-step-functions#14]
When deploying the Step function with Context execution id "AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID.$": "$$.Execution.Id"  its deploying as "$.Execution.Id". which leads to failure of step function.

**Comment by antonbabenko** [comment]
It is better to ask general AWS-related questions in specialized places (like stackoverflow or various Slacks)
