### ISSUE TITLE
Error: Invalid for_each argument

### ISSUE THREAD

**Issue by mliner** [terraform-aws-modules/terraform-aws-step-functions#20]
## Description

Hey, I am using the step-functions module in my application and I am having this issue:

`│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/state-machine/main.tf line 76, in data "aws_iam_policy_document" "service":
│   76:   for_each = local.create_role && var.attach_policies_for_integrations ? try(tomap(var.service_integrations), var.service_integrations) : tomap({})
│     ├────────────────
│     │ local.create_role is true
│     │ var.attach_policies_for_integrations is true
│     │ var.service_integrations is object with 2 attributes
│ 
│ The "for_each" value depends on resource attributes that cannot be
│ determined until apply, so Terraform cannot predict how many instances will
│ be created. To work around this, use the -target argument to first apply
│ only the resources that the for_each depends on.
╵`

I am not entirely sure why this happens because I am using only standard available service integrations.
## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions
 - Terraform: ~>0.14
 - Provider(s): aws - v3.44.0
 - Module: 2.3.0

### Code Snippet to Reproduce
` service_integrations = {
    lambda = {
      lambda = [
        module.lambda1.lambda_arn,
        module.lambda2.lambda_arn,
        module.lambda3.lambda_arn
      ]
    }
    ecs_Sync = {
      ecs    = [module.fargate.task_definition_arn]
      events = ["arn:aws:events:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:rule/StepFunctionsGetEventsForECSTaskRule"]
    }
  }

  attach_policy_json = true
  policy_json        = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "iam:PassRole",
      "Resource": "*",
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
POLICY`

## Actual behavior
Failing on:
`╷
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/state-machine/main.tf line 76, in data "aws_iam_policy_document" "service":
│   76:   for_each = local.create_role && var.attach_policies_for_integrations ? try(tomap(var.service_integrations), var.service_integrations) : tomap({})
│     ├────────────────
│     │ local.create_role is true
│     │ var.attach_policies_for_integrations is true
│     │ var.service_integrations is object with 2 attributes
│ 
│ The "for_each" value depends on resource attributes that cannot be
│ determined until apply, so Terraform cannot predict how many instances will
│ be created. To work around this, use the -target argument to first apply
│ only the resources that the for_each depends on.`

**Comment by antonbabenko** [comment]
Unfortunately, you hit a limitation of Terraform which is described here - https://github.com/hashicorp/terraform/issues/4149

The solution is:
> To work around this, use the -target argument to first apply only the resources that the for_each depends on.

**Comment by mliner** [comment]
@antonbabenko thanks, but it is not entirely clear for me why it happens now, because this issue is happening only when I am applying it via pipeline (bitbucket in this case). when I do a plan and apply localy everything works correctly. So it might be an issue of some library version or so?

**Comment by antonbabenko** [comment]
This issue was there since the early days of Terraform. The difference you experience can be related to the fact that different environments (on CI and when running locally) starting from different bases. One environment has Lambda function already created and it succeeds.

**Comment by mliner** [comment]
@antonbabenko I've applied all lambdas (that are part of the service_intergrations) - also tried to add depends_on statement in the step-functions in order to wait for lambdas to create but still getting the error:
`Error: Invalid for_each argument

  on .terraform/modules/state-machine/main.tf line 76, in data "aws_iam_policy_document" "service":
  76:   for_each = local.create_role && var.attach_policies_for_integrations ? try(tomap(var.service_integrations), var.service_integrations) : tomap({})

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.`

**Comment by antonbabenko** [comment]
Make sure that you apply all resources/modules mentioned in `service_integrations` (not just Lambdas). You also have `module.fargate.task_definition_arn` mentioned there. `depends_on` won't help unfortunately.

**Comment by faresz** [comment]
The problem here `for_each = local.create_role && var.attach_policies_for_integrations ? try(tomap(var.service_integrations), var.service_integrations) : tomap({})` 
is simply that terraform needs the left and right results (from the condition ... ? <left result> : <right result>)  for maps to be with the same structure, and if you provide an empty structure for the right result you will can never skip the block.

Why we don't simply replace this line of code by the below and it will fix the problem

  for_each = {
    for key, value in var.service_integrations : key => value
    if local.create_role && var.attach_policies_for_integrations && value != null
  }

**Comment by davidski** [comment]
Please keep this issue open. This is a major problem using this module.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.5.2 :tada:
