### ISSUE TITLE
Docs about ECS integration

### ISSUE THREAD

**Issue by lays147** [terraform-aws-modules/terraform-aws-step-functions#31]
## Is your request related to a new offering from AWS?
Nope

## Is your request related to a problem? Please describe.
Kinda. I'm trying to make a state machine using ecs-fargate, and I'm getting IAM errors that I see that are related to #11. But I can't figure out what I need to do in `service_integrations` to connect ecs to the step function. 
Apparently #19 fixed the integration, but the README wasn't updated :cry: 

## Describe the solution you'd like.
Add to the docs or the examples a snippet on how to use it with ECS.

**Comment by lays147** [comment]
cc @antonbabenko

**Comment by antonbabenko** [comment]
Hi @lays147 !

I don't have the capacity to look into this issue in the near future.

Please make sure that you check the code in the [examples/complete folder](https://github.com/terraform-aws-modules/terraform-aws-step-functions/tree/master/examples/complete) and provide the required details when you create an issue.
