### ISSUE TITLE
Make it easier to use service integrations that require events permissions

### ISSUE THREAD

**Issue by Octogonapus** [terraform-aws-modules/terraform-aws-step-functions#33]
## Is your request related to a new offering from AWS?
No, this relates to an existing offering.

## Is your request related to a problem? Please describe.
I would like it to be easier to use service integrations that require `events` permissions. E.g. the step functions integration. Without setting the proper events permissions, you will get an error similar to this: `Error: AccessDeniedException: 'arn:aws:iam::xxxx:role/step-functions-role' is not authorized to create managed-rule.`. This has caused prior issues like #11 (which was also related to other permissions issues addressed in #19 and #24).

## Describe the solution you'd like.
Add the relevant `default_resources` to each `events` block inside the `aws_service_policies` such that users can write `events = true` for services that require these permissions.
Custom resources must be allowed, if the requires it.

## Describe alternatives you've considered.
Currently, users must write out the full resources for the `events` permissions. This works, but it is verbose and repetitive.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.6.0 :tada:
