### ISSUE TITLE
Add aws/vendedlogs/states prefix to cloudwatch_log_group_name variable

### ISSUE THREAD

**Issue by EternoSurmenage** [terraform-aws-modules/terraform-aws-step-functions#36]
## Is your request related to a new offering from AWS?

No
## Is your request related to a problem? Please describe.

When the Cloudwatch resource policy reaches the size limit, terraform deploy will fail with misleading errors coming from AWS. One is _IAMRole denied exception for log destination_ and _LimitExceededException_.

By default, the variable `cloudwatch_log_group_name` is null, so unless the user knows about it and specifies it, the log group will be created at the root level of CloudWatch.
## Describe the solution you'd like.

As stated in [the official documentation](https://docs.aws.amazon.com/step-functions/latest/dg/bp-cwl.html), we need a way to attach the `/aws/vendedlogs/states/` prefix in the group name of the resource if `cloudwatch_log_group_name` is not defined by the user.

So, instead of the current coalesce instruction:
https://github.com/terraform-aws-modules/terraform-aws-step-functions/blob/3f974cce601d34ea129053a4e4a8a83ac206a69e/main.tf#L296-L304
it could be replaced with something like:
  ` name              = coalesce(var.cloudwatch_log_group_name, "/aws/vendedlogs/states/${var.name}")`
## Describe alternatives you've considered.

- If changing the coalesce instruction is not possible, then add a prefix variable/constant that should be automatically concatenated to the group name
- If the above is not possible, make `cloudwatch_log_group_name` required.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 3.1.0 :tada:
