### ISSUE TITLE
Object Timeouts

### ISSUE THREAD

**Issue by josephpohlmann** [terraform-aws-modules/terraform-aws-step-functions#51]
Similar to the AWS Firehose (which was addressed, see:  https://github.com/hashicorp/terraform-provider-aws/issues/22645), it is possible that an AWS StepFunction may time out before the object was successfully created or destroyed.

As such, this module should support the "timeouts" stanza.  Something like:

  timeouts {
    create = "15m"
    update = "10m"
    delete = "15m"
  }

**Comment by antonbabenko** [comment]
It does not seem to have support in the Terraform AWS provider. Please open an issue there.
