### ISSUE TITLE
Permission denied when calling step function within step function in standard workflow using sync pattern

### ISSUE THREAD

**Issue by lbednaszynski** [terraform-aws-modules/terraform-aws-step-functions#59]
PR https://github.com/terraform-aws-modules/terraform-aws-step-functions/pull/58 introduced bug - now it is not possible to call step function within step function in standard workflow using sync pattern due permission denied error.

I pressume that action should depends on workflow type: for express workflows it should be states:StartSyncExecution but for standard workflows it should be states:StartExecution.

**Comment by antonbabenko** [comment]
There are two groups of permissions depending on the workflow types. You should be able to accomplish what you need by choosing the right option.

One:
https://github.com/terraform-aws-modules/terraform-aws-step-functions/blob/ef271305ebcc138e3047a9dea2455c429d439b65/locals.tf#L701-L724

Two:
https://github.com/terraform-aws-modules/terraform-aws-step-functions/blob/ef271305ebcc138e3047a9dea2455c429d439b65/locals.tf#L726-L732

**Comment by lbednaszynski** [comment]
It seems that option two works but honestly I do not why. Both links that I attached below mentions that .sync call (event when calling StartExecution) needs additional permissions to monitor execution progress and has ability to stop execution.

1. https://docs.aws.amazon.com/step-functions/latest/dg/connect-stepfunctions.html
2. https://docs.aws.amazon.com/step-functions/latest/dg/stepfunctions-iam.html#sync-async-iam-policies

**Comment by antonbabenko** [comment]
I took the IAM docs from the official page for both types - https://docs.aws.amazon.com/step-functions/latest/dg/stepfunctions-iam.html

If you think something is missing, please open a PR (and attach a link to the official documentation for reference).

**Comment by TLaue** [comment]
I am having the same problem in our project. Until version 4.0.0 everything worked without any problems but with the latest change from "states:StartExecution" to "states:StartSyncExecution" all standard workflows broke. All sync executions of nested workflows are nor longer possible due to an IAM permission issue.

**Comment by XnS** [comment]
We're also facing the IAM permission issue(s) since v4.0.1
