### ISSUE TITLE
Service integration policies cause race-condition with Step Function creation/modification

### ISSUE THREAD

**Issue by GiamPy5** [terraform-aws-modules/terraform-aws-step-functions#61]
## Description

When creating a Step Function using the service integration policies provided by the module, there's a race condition which causes the Step Function creation/update to be triggered before policies are successfully created, causing an error:

```
│ Error: updating Step Functions State Machine (arn:aws:states:eu-central-1:obfuscated-account-id:stateMachine:obfuscated-step-function-name): AccessDeniedException: 'arn:aws:iam::obfuscated-account-id:role/obsfucated-role' is not authorized to create managed-rule.
│       status code: 400, request id: df276253-c571-45cf-8865-04b99a7ff0f5
│ 
│   with module.step_function.aws_sfn_state_machine.this[0],
│   on .terraform/modules/step_function/main.tf line 15, in resource "aws_sfn_state_machine" "this":
│   15: resource "aws_sfn_state_machine" "this" {
│
```

If your request is for a new feature, please use the `Feature request` template.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 3.1.0
- Terraform version: 1.5.5
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v5.5.0
```

## Reproduction Code [Required]

```
data "aws_caller_identity" "current" {}

data "aws_region" "current" {}

locals {
  codebuild_events_arn = "arn:aws:events:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:rule/StepFunctionsGetEventForCodeBuildStartBuildRule"
}

module "step_function" {
  source  = "terraform-aws-modules/step-functions/aws"
  version = "3.1.0"

  name = var.step_function_name

  type = "standard"

  definition = templatefile("${path.module}/template.asl.json", {
    [...]
  })

  logging_configuration = {
    include_execution_data = true
    level                  = "ALL"
  }

  service_integrations = {
    xray = {
      xray = var.enable_xray_integration
    }

    codebuild_StartBuild_Sync = {
      codebuild = [
        var.codebuild_arn
      ]
      events = [local.codebuild_events_arn]
    }

    stepfunction_Sync = {
      stepfunction = [var.foo_step_function_arn, var.bar_step_function_arn]
      events       = true
    }

    lambda = {
      lambda = [
        var.lambda_foo_function_arn,
        var.lambda_bar_function_arn
      ]
    }
  }
}
```

Are you using workspaces? No.
Have you cleared the local cache (see Notice section above)?: Yes
List steps in order that led up to the issue you encountered:

- simply run terraform plan and apply

## Expected behavior

The policies should be created before the step function is created.

## Actual behavior

The step function creation fails because the policy was not created successfully before the step function.

### Terminal Output Screenshot(s)

![image](https://github.com/terraform-aws-modules/terraform-aws-step-functions/assets/4460702/c2907aca-7a09-4ea6-a6c8-94caf542676a)

## Additional context

As you can see, the step function starts the modification BEFORE the policy has been created. By running it a second time, the apply works without issues.

**Comment by antonbabenko** [comment]
Please try upgrading Terraform AWS provider to be newer than 5.11.0 (you have 5.5.0). Also, the code in the module is written in the way that it handles dependencies between resources correctly (StepFunction machine, IAM role, IAM policy, IAM policy attachment), so there is nothing we should be doing in the module but rather in provider.

Please open issue in the provider repository.
