### ISSUE TITLE
Support for CloudWatch Event Rule (based on a schedule)

### ISSUE THREAD

**Issue by atrakic** [terraform-aws-modules/terraform-aws-step-functions#7]
## Is your request related to a new offering from AWS?

Yes, it should be available with current tf aws provider.

## Is your request related to a problem? Please describe.

No, this a pure feature request to extend module usage.

## Describe the solution you'd like.

I would hereby suggest integration within this module by using CloudWatch Event Rule, which would trigger the state machine based on a schedule. An optional parameter (cron expression would be just fine). 

## Additional context

My goal is to run a Fargate task-definition but in scheduled manner, eg: https://docs.aws.amazon.com/step-functions/latest/dg/sample-project-container-task-notification.html

**Comment by atrakic** [comment]
Just tried to use with modified fargate definition but I fail to understand how to use service_integrations` variable? I need to add IAM permission for ecs and ssm. Thx in advance

**Comment by antonbabenko** [comment]
You can see how to use `service_integrations` in [README](https://github.com/terraform-aws-modules/terraform-aws-step-functions#service-integration-policies).

`service_integrations` define a preset of IAM policy required for your step function. Looking into [IAM example](https://docs.aws.amazon.com/step-functions/latest/dg/sample-project-container-task-notification.html#sample-container-iam-example), the code should look something like this:

```terraform
module "step_function" {
  source = "terraform-aws-modules/step-functions/aws"

  # ... omitted

  service_integrations = {
    ecs_Sync = {
      ecs = "arn:aws:ecs:ap-northeast-1:123456789012:task-definition/FargateTaskNotification-ECSTaskDefinition-13YOJT8Z2LY5Q:1"
      ecs_Wildcard = true
      events = "arn:aws:events:ap-northeast-1:123456789012:rule/StepFunctionsGetEventsForECSTaskRule"
    }

    sns = {
      sns = "arn:aws:sns:ap-northeast-1:123456789012:FargateTaskNotification-SNSTopic-1XYW5YD5V0M7C"
    }
  }
}
```

Hopefully, it helps you.

**Comment by atrakic** [comment]
I managed to apply with: 
```
....
  attach_policy = true
  policy        = "arn:aws:iam::aws:policy/CloudWatchEventsFullAccess"
  attach_policy_json = true
  policy_json        = <<-EOF
  {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecs:RunTask"
            ],
            "Resource": [
                "arn:aws:ecs:${local.self["region"]}:${local.self["account_id"]}:task-definition/ping"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ecs:StopTask",
                "ecs:DescribeTasks"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
              "sns:Publish"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "events:PutTargets",
                "events:PutRule",
                "events:DescribeRule"
            ],
            "Resource": [
               "arn:aws:events:${local.self["region"]}:${local.self["account_id"]}:rule/StepFunctionsGetEventsForECSTaskRule"
            ]
        }
    ]
  }
  EOF
```
As described here: https://docs.aws.amazon.com/step-functions/latest/dg/ecs-iam.html. Thx anyway.
