### ISSUE TITLE
Is there support to enable Cloudwatch logging?

### ISSUE THREAD

**Issue by ahummel25** [terraform-aws-modules/terraform-aws-step-functions#8]
Just wondering if there is any way to enable Cloudwatch logging for my step function using this module. Not necessarily requesting that feature, but just more curious if I missed it in the docs.

Thanks!

**Comment by ahummel25** [comment]
I think I just answered my own question by looking at the actual aws_sfn_state_machine TF resource. 😆

**Comment by ahummel25** [comment]
There is a `logging_configuration` parameter in the underlying aws_sfn_state_machine resource. Looks like that is not supported here?

**Comment by antonbabenko** [comment]
Good point, there is no support for logging in this module, yet. PR is welcome.

**Comment by ahummel25** [comment]
@antonbabenko Can you grant me access to push to this repo?

**Comment by antonbabenko** [comment]
Please open pull-request to this repository from your own fork for review.
